target-version = "py311"

[lint]
select = [
    "B",
    "C",
    "COM",
    "E",
    "F",
    "I",
    "INP",
    "RET",
    "S",
    "T",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "C901",
    "E501",
    "T2",
    "TRY003",
]

[lint.per-file-ignores]
"**/test*.py" = ["S101"]  # tests can use assertions
